### ISSUE TITLE
Unable to use the style

### ISSUE THREAD

**Issue by stalkerGH** [geometalab/uep-kt-zh#6]
I have a simple question how can I apply the style. Could you please point me to some guide? I have Maptiler free account and API key. I hardcoded API key in local copy of JSON file. What should I do next?

**Comment by sfkeller** [comment]
Hi, 
Thanks for asking.
This repo was also only intended for internal use.
What I can offer is this style for the canton of Zurich, which we made for QGIS based on OSM: https://github.com/geometalab/QgisStyleKtZH . Unfortunately, we hardly have time to offer support for this.

**Comment by stalkerGH** [comment]
Thank you, I will look to above link.
